[tool.poetry]
name = "packages.geoip"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
packages = [{include = "geoip", from = ".."}]
include = ["GeoIP2-City.mmdb"]

[tool.poetry.dependencies]
python = "^3.9"
"packages.ip" = {path = "../ip", develop = true}
geoip2 = "^4.4.0"
maxminddb = "^2.2.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
